path: /content/gdrive/MyDrive/GAN Assignment/data # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: Breadcrumb 
  1: checkbox 
  2: container 
  3: dropdown 
  4: Forms 
  5: buttons
  6: logo images
  7: Navigation dots 
  8: text 
  9: links 
  10: input fields 
  11: radio 
  12: modal
  
